name: Incorrect Weapon
description: Report an incorrect weapon assigned to a tank.
title: "[Incorrect Weapon]: "
labels: ["database-issue", "incorrect-weapon"]
body:
  - type: input
    id: tank_id
    attributes:
      label: Tank ID
      description: |
        Please provide the Tank ID.  
        You can find the Tank ID by opening `Tank_DB.json`, locating the tank entry, and copying the `"id"` field or using the warthunder wiki.
      placeholder: e.g. ussr_t_26_1940
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description (optional)
      description: Provide any extra details about the incorrect weapon.
      placeholder: e.g. "The ussr_t_26_1940 will not work due to incorrect weapon"
    validations:
      required: false
